name: Selenium IDE CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3
  steps:
    - name: SetUp .Net Core
      uses: actions/checkout@v3
      with:
	dotnet-version: '6.0.x'
  
    - name: Install nuget packages
      run: dontnet restore
    - name: Build test project
      run: dontnet build --no-restore
    - name: Run tests
      run: dotnet tests	
		





	